### ISSUE TITLE
If check on PUMAs state prevents pull of Tiger data

### ISSUE THREAD

**Issue by Joshkking** [walkerke/pygris#7]
There is an if statement in `enumeration_units.py` in the `puma` function that prevents the download of the full US PUMA shapefiles as a Tiger dataset.

That code follows:

```
if state is None:
    if year == 2019 and cb:
        state = "us"
        print("Retrieving PUMAs for the entire United States")
    else:
        raise ValueError("A year must be specified for this year/dataset combination.")
else:
    state = validate_state(state)
```

As I understand, the way to pull all of the US is to leave `state=None`; however, you can see in the above that the only way to do that is through the narrow combination of `year == 2019 and cb`. I have also tried queries such as `state='us', year=2019` which complains of an invalid state. My thinking is the if statement referenced above generally is enforcing beyond its original intention.

This makes for a slightly confusing user interface to spin the wheels on, but also the limit against Tiger may not be preferred. For instance, in my case, grabbing the Tiger shape file's very handy internal latitude and longitude points is required.

Anyways, seemed like a quick fix possibility. @walkerke Thanks for this great resource!

**Comment by Joshkking** [comment]
Also just noticed it seems like an "all US" download of PUMAs might not be available? If so, suggestion of changing the error message to better reflect the reality or invoking a loop across all US state codes followed by a concatenation of the returned geoframes.

**Comment by walkerke** [comment]
HI @Joshkking,

You are correct - the only national PUMA file Census currently makes available is the 2019 CB file, which is why all of your other requests fail.  

We could put some code internally to allow for national PUMA pulls.  Please note that Census has not released CB PUMA files for 2020 through 2022.  It'd work something like this:

```python
from pygris import pumas, fips_codes
from pygris.utils import shift_geometry
import pandas as pd

fips = fips_codes()

all_states = [code for code in fips['state_code'].unique().tolist() if code <= "56"]

all_pumas = pd.concat([pumas(x, year = 2022, cache = True) for x in all_states])

shift_geometry(all_pumas).plot()
```

![image](https://user-images.githubusercontent.com/4872833/233388168-4951e312-515f-400d-9e27-ee0eeb46eefa.png)

**Comment by Joshkking** [comment]
@walkerke That seems wise. That's honestly ~ what I did in the interim for my own purposes!
